### ISSUE TITLE
Support verifying that a leaf of type empty is present or not in ActionRequest.Input 

### ISSUE THREAD

**Issue by sebastien-guay** [freeconf/restconf#21]
Support verifying that a `leaf `of type `empty` is present or not in `ActionRequest.Input`.

Currently, calling `req.Input.GetValue(...)` will always return `nil` whatever the leaf is there or not.

Having something like `req.Input.HasLeaf(name)` would be nice.

**Comment by dhubler** [comment]
I created branch `issue-21` with fix to checkout.  `GetValue()` should return something now.  `GetValue() == val.NotEmpty` in fact

**Comment by dhubler** [comment]
I'll merge this in few days if i do not hear from you otherwise that this doesn't work for you

**Comment by sebastien-guay** [comment]
> I'll merge this in few days if i do not hear from you otherwise that this doesn't work for you

I don't see the `issue-21` branch but returning val.NotEmpty looks good.

**Comment by sebastien-guay** [comment]
Hi @dhubler!

Is this issue has been resolved?

**Comment by dhubler** [comment]
yes, but i forgot to merge.  should be in master now
