### ISSUE TITLE
Set content-type to application/yang-data+json as specified in RFC8040 

### ISSUE THREAD

**Issue by sebastien-guay** [freeconf/restconf#29]
The current content-type in a POST response is set to application/json.

According to RFC8040 it must be application/yang-data+xml or application/yang-data+json. In our case it is application/yang-data+json.

See https://www.rfc-editor.org/rfc/rfc8040.html#section-3.2

**Comment by dhubler** [comment]
merged (with minor tweak) thanks!  
Ideally squash commits before submitting.  If I squash them, then it erases author tag.

**Comment by sebastien-guay** [comment]
> 

Thanks!
