### ISSUE TITLE
typedef empty not found

### ISSUE THREAD

**Issue by pdumais** [freeconf/restconf#3]
when adding a leaf, in the car example, with "type empty", I get the error: typedef empty not found

**Comment by pdumais** [comment]
in https://github.com/freeconf/yang/blob/8b33f4842e6b8e2605454265fe0b6cf283f85571/val/format.go#L53
internalTypes is missing a mapping for Empty

**Comment by pdumais** [comment]
There is also no support for outputting a "binary" format. I've changed this also in my PR

**Comment by dhubler** [comment]
commit 2aee1f98cdbeb2183fb082b826a31674d04d633e
Author: Pat Dumais <githum@dumais.io>
Date:   Wed Aug 17 10:01:16 2022 -0400

    Adding support for binary type

commit 209bc538fbef953a6ee9141d42d7b73ac8673b0b
Author: Pat Dumais <githum@dumais.io>
Date:   Tue Aug 16 13:40:41 2022 -0400

    Missing 'empty' mapping
