### ISSUE TITLE
Feature request: Improve error handling

### ISSUE THREAD

**Issue by rFronteddu** [freeconf/restconf#41]
I noticed that when restconf panics due to the use of a wrong type for reflection it does not print the name of the field that caused the problem but only the type. I think it could simplify debugging to have access to that information

**Comment by dhubler** [comment]
I agree.  I have started to fix this issue when I see it and may have just
fixed this in a branch I'm about to merge in  next week or so.  If you
reply w/the specific error and case, I can check.

**Comment by rFronteddu** [comment]
I will keep posting observations while I build a restconf interface.

For starters, something that was not immediate to me is that ApplyStartupConfig seems to not create [] or maps in the managed object. If a configuration is present for the map/[], I would let ApplyStartupConfig do the creation.

If the map/map is not created, restconf only reports that there was a nil assignment to map/vector. It would probably simplify the debug process if we always printed the field under examination.

**Comment by rFronteddu** [comment]
I was playing with your map example (https://freeconf.org/docs/examples/node-list-map/) and if in your go struct you forget one of the fields, restconf tells you that a field is missing but it doesn't tell you where or which one.

**Comment by dhubler** [comment]
Just an update that this is still progressing.  Should be next week
sometime.

**Comment by rFronteddu** [comment]
Thank you for the update!

**Comment by dhubler** [comment]
I just pushed an update but instead of changing nodeutil.Reflect I created nodeutil.Node which you should check out.  Easier and more powerful to use.  It does have better error handling and should give field names.
Docs: https://freeconf.org/docs/examples/node-reflect/
You can reopen this if you still have issues

**Comment by rFronteddu** [comment]
Thank you! Just in time, I got sidetracked again but I will work again on this project this week!
