### ISSUE TITLE
Response content type not correctly set after XML pull request merge

### ISSUE THREAD

**Issue by sebastien-guay** [freeconf/restconf#51]
Response content type not correctly set after XML pull request merge. 

The current code on master is calling browser_handler::setContentType(). See https://github.com/freeconf/restconf/blob/1ccf8121832a626730382ef59eb6a488dcde6d35/browser_handler.go#L206

It must calls util::setResponseContentType() .

**Comment by dhubler** [comment]
I was able to duplicate that Accept of xml accept did indeed not return xml as content-type (was always json).

I have been working on the xml branch quite a lot as I work on NETCONF support and stabilized it enough to merge it into master so you'll find the fix there.
