### ISSUE TITLE
local.go:ApplyStartupConfigFile function panics instead of returning an error

### ISSUE THREAD

**Issue by Kirhchoff** [freeconf/restconf#52]
ApplyStartupConfigFile from local.go file currently panics when something goes wrong opening the config file (for instance when we provide an incorrect startup file path). This prevents applications from properly handling errors. It is also not in line with the function signature, which suggests it should return errors when something goes wrong

Current implementation:
https://github.com/freeconf/restconf/blob/master/device/local.go#L112
```
func (self *Local) ApplyStartupConfigFile(fname string) error {
	cfgRdr, err := os.Open(fname)
	defer cfgRdr.Close()
	if err != nil {
		panic(err)
	}
	return self.ApplyStartupConfig(cfgRdr)
}
```

**Comment by Kirhchoff** [comment]
I've prepared a PR for the issue https://github.com/freeconf/restconf/pull/53

**Comment by dhubler** [comment]
applied, thank you.
