### ISSUE TITLE
Restconf does not set the body in the right format (XML) for errors with a body when the accept in the request is XML

### ISSUE THREAD

**Issue by sebastien-guay** [freeconf/restconf#54]
Restconf does not set the body in the right format (XML) for errors with a body when the accept in the request is XML. The response is always in JSON.

The merge request for XML were including the required code in util.go but it has not been taken.

**Comment by dhubler** [comment]
I see the approach I took didn't account for errors.  I'll have it fixed in
the next few days.

**Comment by dhubler** [comment]
should be fixed now.
