### ISSUE TITLE
Restconf go.mod does not refer to latest freeconf/yang

### ISSUE THREAD

**Issue by sebastien-guay** [freeconf/restconf#55]
Restconf go.mod does not refer to the latest freeconf/yang with commit:

https://github.com/freeconf/yang/commit/991b7759d7927f8ba7f31df94bb762bf0f8d140d

With this change freecong/nodeutil/json_rdr.go is returning two values and the current code in browser_handler.go is also expecting two values but restconf/go.mod is pointing to an older version of freeconf/yang.

**Comment by dhubler** [comment]
fixed, thanks for reporting.  

Background: I use Go workspaces which has unfortunate side effect of ignoring go.mod so i tend to miss things like this.  I am going to work on a script to automate this because this affects other repos as well.
