### ISSUE TITLE
Response body for errors not valid in XML

### ISSUE THREAD

**Issue by sebastien-guay** [freeconf/restconf#57]
Here is an example of an errors body in xml:

```
<errResponseWrapper>
   <errors>
      <error>
         <error-type>protocol</error-type>
         <error-tag>access-denied</error-tag>
         <error-path>ietf-sztp-bootstrap-server:report-progress</error-path>
         <error-message>Bad ACL not authorized</error-message>
      </error>
   </errors>
</errResponseWrapper>
```
errResponseWrapper should not be there and xmlns must be set to "urn:ietf:params:xml:ns:yang:ietf-restconf"

https://github.com/freeconf/restconf/blob/9848fef17a9f8023f312d03dcef3f607aa408033/util.go#L87

**Comment by dhubler** [comment]
fixed
See files for example responses
https://github.com/freeconf/restconf/blob/master/testdata/gold/error.xml
https://github.com/freeconf/restconf/blob/master/testdata/gold/error.json
