### ISSUE TITLE
Edit a leaf with `config false`

### ISSUE THREAD

**Issue by pj-99** [freeconf/restconf#58]
Hello, I try to use the following yang file to test `config-false`:
```yang
module hello {
	leaf message {
		type string;
	}

	leaf config-false-message {
		type string;
		config false;
	}
}

```
And then I POST to `http://localhost:8080/restconf/data/hello:` with the body:
```json
{"config-false-message":"test"}
```
I observed that the POST method successfully edited the "config-false-message".

However, based my understanding from [dicussion](https://github.com/orgs/freeconf/discussions/24#discussioncomment-5350204) and [RFC 6020-YANG](https://datatracker.ietf.org/doc/html/rfc6020#section-4.2.3), the leaf marked with `config false` cannot be manipulated by POST or other method. 

Could you please confirm if this behavior is expected?

Thank you very much.

**Comment by dhubler** [comment]
confirmed this is an issue.  great catch, hard to believe this wasn't caught sooner. Should have fix in next 24hrs on master branch.
