### ISSUE TITLE
Bug in support for RFC 8525

### ISSUE THREAD

**Issue by b-kamphorst** [freeconf/restconf#60]
Hi!

If I interpret [the supported](https://freeconf.org/docs/reference/compliance/rfcs/) [RFC 8525](https://datatracker.ietf.org/doc/html/rfc8525) correctly, the container `modules-state` from `restconf/data/ietf-yang-library` is deprecated in favor of a container `yang-library`. However, when I call the endpoint on the Car example, the reply contains `modules-state` but not `yang-library`. Is this a bug?

**Comment by dhubler** [comment]
i think this area has not received a lot of interop testing, so if you see
something that looks off, it likely is.

**Comment by b-kamphorst** [comment]
Thank you for the swift reply. I find an excuse to work on this (no guarantees), I could make a PR. Would you be open to that? From what I can see, this issue requires extending [device/yang_lib_node.go](https://github.com/freeconf/restconf/blob/master/device/yang_lib_node.go) and [device/yang_lib_test.go](https://github.com/freeconf/restconf/blob/master/device/yang_lib_test.go). Would you agree?

**Comment by dhubler** [comment]
absolutely.  Yes, those appear to be the right files.
